meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/autoware-safety-island-example/src/safety_island_bringup/launch/safety_island.launch.xml
    sha256: aa6042937097a781a6d91b01782ac772f0540abb78ad2527a6b6dd2a785c87d4
  - path: /home/aeon/repos/autoware-safety-island-example/src/safety_island_bringup/system.toml
    sha256: 0cc10128fe6a6a36f72fc8b384b4de1f8daf227f57e5e4ffba31dd6ce35ed6e2
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    safety_island.launch.xml:
      file: safety_island.launch.xml
  nodes:
    /mrm_comfortable_stop_operator:
      scope: safety_island.launch.xml
      pkg: autoware_mrm_comfortable_stop_operator
      exec: mrm_comfortable_stop_operator
      node_name: mrm_comfortable_stop_operator
    /mrm_emergency_stop_operator:
      scope: safety_island.launch.xml
      pkg: autoware_mrm_emergency_stop_operator
      exec: mrm_emergency_stop_operator
      node_name: mrm_emergency_stop_operator
    /mrm_handler:
      scope: safety_island.launch.xml
      pkg: autoware_mrm_handler
      exec: mrm_handler
      node_name: mrm_handler
    /stop_mode_operator:
      scope: safety_island.launch.xml
      pkg: autoware_stop_mode_operator
      exec: stop_mode_operator
      node_name: stop_mode_operator
execution:
  deploy:
    /mrm_comfortable_stop_operator:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /mrm_emergency_stop_operator:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /mrm_handler:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /stop_mode_operator:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
