meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/autoware-safety-island-example/src/safety_island_bringup/launch/safety_island.launch.xml
    sha256: da7a21e847534388e454d8c67357dfc36147f452d8208d4884ab4b5cad1ac2f5
  - path: /home/aeon/repos/autoware-safety-island-example/src/safety_island_bringup/system.toml
    sha256: 76c4c2ceb1dafac28b35765b1b43016803f59c22216c2bccf9bb725da0590979
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    safety_island.launch.xml:
      file: safety_island.launch.xml
  nodes:
    /mrm_comfortable_stop_operator:
      scope: safety_island.launch.xml
      pkg: autoware_mrm_comfortable_stop_operator
      exec: mrm_comfortable_stop_operator
      node_name: mrm_comfortable_stop_operator
    /mrm_emergency_stop_operator:
      scope: safety_island.launch.xml
      pkg: autoware_mrm_emergency_stop_operator
      exec: mrm_emergency_stop_operator
      node_name: mrm_emergency_stop_operator
    /stop_mode_operator:
      scope: safety_island.launch.xml
      pkg: autoware_stop_mode_operator
      exec: stop_mode_operator
      node_name: stop_mode_operator
execution:
  deploy:
    /mrm_comfortable_stop_operator:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /mrm_emergency_stop_operator:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /stop_mode_operator:
      target: linux
      domain: 2
      rmw: cyclonedds
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
